<?php

namespace G4\DataRepository;

class ErrorCodes
{

    const MISSING_STORAGE_INSTANCE_EXCEPTION    = 30001;
    const NOT_VALID_STORAGE_EXCEPTION           = 30002;
    const MISSING_MAPPER_INSTANCE_EXCEPTION     = 30003;
    const MISSING_ACTION_EXCEPTION              = 30004;
    const MISSING_IDENTITY_EXCEPTION            = 30005;
    const MISSING_RUSSIAN_DOLL_EXCEPTION        = 30006;
    const MISSING_IDENTITY_MAP_KEY_EXCEPTION    = 30007;
    const INVALID_QUERY_EXCEPTION               = 30008;
    const MISSING_CUSTOM_COMMAND_EXCEPTION      = 30009;
}
