<?php

namespace G4\DataRepository;

class ErrorCodes
{

    const MISSING_STORAGE_INSTANCE_EXCEPTION    = 30001;
    const NOT_VALID_STORAGE_EXCEPTION           = 30002;
    const MISSING_MAPPER_INSTANCE_EXCEPTION     = 30003;
    const MISSING_ACTION_EXCEPTION              = 30004;
    const MISSING_IDENTITY_EXCEPTION            = 30005;
    const MISSING_RUSSIAN_DOLL_EXCEPTION        = 30006;
    const MISSING_IDENTITY_MAP_KEY_EXCEPTION    = 30007;
    const INVALID_QUERY_EXCEPTION               = 30008;
    const MISSING_CUSTOM_COMMAND_EXCEPTION      = 30009;
    const MISSING_RESPONSE_TOTAL                = 30010;
    const MISSING_RESPONSE_COUNT                = 30011;
    const MISSING_RESPONSE_ALL_DATA             = 30012;
    const MISSING_RESPONSE_ONE_DATA             = 30013;
    const MISSING_DATASET_NAME_VALUE_EXCEPTION  = 33014;
}
